### ISSUE TITLE
BookFederationTutorial seems out of date

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#100]
I was trying to get Teiid running for the purpose of using a CSV file to populate an ontology. I ran into multiple problems:

1. The version (8.11) listed in the link to JBoss was not found. I finally decided to go with version 8.13.
2. The instructions given for the installation of the JBoss integration stack did not work. I had to use the eclipse marketplace to install the tools. I have no idea if the marketplace version works.
3. the BookFederation Tutorial gives directions for connecting to Postgres, but the data you have us download is an H2 database. 

For whatever reason, I could not get the Teiid designer in eclipse to connect to the H2 books database. Perhaps the connection string wrong? Here is what I'm using:

jdbc:h2:tcp://localhost/./books

If this is not right, then some instructions should be given on how to connect to the books H2 database. Plus, given the problems in obtaining the JBoss and Teiid discussed in 1 and 2 above, I am not sure what the source of the problem connecting to the database is. So, I am giving up, for now, on this tutorial.

I think Ontop has the potential to be a really good product, and I encourage you to keep on developing it. But, the BookFederation tutorial for using Teiid is either too out of date or needs to be re-written for users, such as myself, who are not familiar with JBOSS and Teiid.

Bill

**Comment by ugurdonmez** [comment]
Thanks for sharing your observations, the installation procedure of Teiid was indeed outdated.

During the last 6 months, a lot of new versions of the Teiid components (runtime, designer) and dependencies (JBoss EAP, WildFly) have been released and it exists some incompatibilities between these versions. For instance, you cannot use the last versions of the Teiid Designer (9.2) and of the Teiid runtime (8.13) together… Please note that it is not simple for us to keep track of all these changes in the installation procedure since we are not often using Teiid.

For working with H2, you have to install the JDBC driver on the JBoss application server. Your connection string is correct. 

We have updated the installation procedure and hope that it will help you to setup Teiid. Of course, if you experience new problems, please let us know.

**Comment by wdduncan** [comment]
Thanks for taking notice of my post. I understand that it is difficult to
keep with changes in Teiid and JBoss. I'll have a look at the new tutorial
(when I get a chance).

Bill

**Comment by ghxiao** [comment]
@wdduncan I close the issue now. Please feel free to reopen it when there is need to continue the discussion.
