### ISSUE TITLE
An error occurred whilst creating the view

### ISSUE THREAD

**Issue by Lanvin2219** [ontop/ontop#114]
NullPointerException:null

If I load an ontology before opening 'Ontop Mappings', I get this error message and I don't know how to solve this. Help is appreciated.

Thanks !

**Comment by skomlaebri** [comment]
Hi, is your error related to one of the following issues?

-  issue #101 in particular to this example https://groups.google.com/forum/#!topic/ontop4obda/KEQrghBedDQ

-  issue #11

If not can you provide a set of steps so that we can reproduce the problem?

**Comment by Lanvin2219** [comment]
I looked at both these errors and I can't reproduce them.

Here's how to reproduce mine : 

1) Open Protégé
2) Open one of those ontologies : 

http://mayor2.dia.fi.upm.es/oeg/files/hrmontology/hrmontology-RDF.zip

3) Switch to 'Ontop Mappings' tab

**Comment by skomlaebri** [comment]
Hi, 
the problem is related to anonymous ontologies. As you can see no **Ontology IR**I appears in the _Active Ontology_ tab  when you open the ontology in Protege. We solved the issue #101 already (it will be in the next release). In the meanwhile if you have the possibility to change the ontologies you can add an ontology IRI for example `http://myontology/competence` directly in Protege in the _Active Ontology_ tab or directly in the ontology file (adding after the prefix declarations` <http://myontology/competence> a owl:Ontology .`)

**Comment by Lanvin2219** [comment]
Thank you very much. It worked after I added the declaration in the file.

**Comment by yurigue** [comment]
an error occurred while creating the view inconsistent ontology  exception: inconsistent ontology

**Comment by yurigue** [comment]
estou resebendo este error não sei como o resolver
