### ISSUE TITLE
multiple property bindings in a mapping can not be saved

### ISSUE THREAD

**Issue by karlisc** [ontop/ontop#120]
I am working with ontop Protege plugin 1.7.1.
I have two mappings, both on the same SQL statement:
select * from XStudent

The mappings are:
:Person-{IDCode} a :Student .
:Person-{IDCode} :studentName {Name} .

This works.

Now I want to group both mappings together. I edit the first one into:
:Person-{IDCode} a :Student , :studentName {Name} .

When I press Update, a lengthy error message appears in the Protege log (see report.txt).
Even if I am doing something wrong, the messages should be more polite ..

Thanks,
Karlis Cerans

[report.txt](https://github.com/ontop/ontop/files/265210/report.txt)

**Comment by skomlaebri** [comment]
Hi,
thanks for reporting the bug, we will provide a better error message to avoid the generation of this kind of mapping.
The union of the two mappings together is possible but it needs a semicolon instead of a colon:
:Person-{IDCode} a :Student **;** :studentName {Name} .
The colon can be used to shorten the mappings when they have the same subject and predicate and different object for example:
:Person-{IDCode}  :studentName {Name} , {Surname} .
