### ISSUE TITLE
deployment guide missing - release 18.0

### ISSUE THREAD

**Issue by bertvannuffelen** [ontop/ontop#123]
Dear,

I am trying to deploy the release 18.0. However I am missing a complete deployment guide. Can someone aids me? I am missing basic information about the deployment of the tool.

I downloaded the files and I unpacked the distribution and then started ./ontop and got the error Error: Could not find or load main class org.semanticweb.ontop.cli.Ontop

For the jetty-bundle: what is the desired startup procedure. The zip contains jetty + some wars and the default jetty instructions. No instructions are found to test whether the startup can be verified whether it is correct. So what is the base url to go to?

kind regards,

Bert

**Comment by bertvannuffelen** [comment]
Dear,

on the ontop script (see https://github.com/ontop/ontop/blob/develop/ontop-cli/src/main/resources/ontop)

1) why using #!/usr/bin/env bash  and not standard #!/bin/bash
   
2) startup java call adapted to 

${JAVA} ${ONTOP_JAVA_ARGS} -cp "${ONTOP_HOME}/lib/*" -Dlogback.configurationFile="${ONTOP_HOME}/log/logback.xml" \
-Djava.ext.dirs="${ONTOP_HOME}/lib/:${ONTOP_HOME}/jdbc/" -jar ${ONTOP_HOME}/lib/ontop-cli-1.18.0.jar $@

removed the error.

**Comment by ghxiao** [comment]
Dear @bertvannuffelen ,

Thanks a lot for your feedbacks. They are very valuable. 

You are right that many documents are still missing/outdated and they are somehow scattered in the wiki. The document is always an ongoing work.

For this CLI class-not-found issue, unfortunately it is clearly a bug introduced in the last minute of release process where we changed some package names. 

It would be great if you can create a pull request for this issue (and possibly also for other issues). In order to merge your contribution, we will need a contribution agreement (see https://github.com/ontop/ontop/blob/develop/CONTRIBUTING.md) . You can send a copy to my email 
"xiao AT inf.unibz.it"

In any case, we will release a hot fix version for solving this issue asap.

Cheers,

**Comment by ghxiao** [comment]
Fixed in 8d74763.

The fixed file is uploaded to sourceforge as

/ontop-1.18.0/ontop-distribution-1.18.0.1.zip

**Comment by bertvannuffelen** [comment]
@ghxiao thanks, I'll have a look.
