### ISSUE TITLE
cli's materialising doesn't seem to include all triples

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#165]
a) using Protégé with owl and obda file
query: 
SELECT * WHERE {<http://data.vlaanderen.be/id/gemeentenaam/200002> ?p ?v.}
result:
p,v
label,"Antwerpen"@nl
gemeenteNaam,"Antwerpen"@nl
gemeenteNaam,"Antwerpen"@de
gemeenteNaam,"Anvers"@fr
type,GemeenteNaam
afgeleidVanGemeente,200002

b) using CLI with same owl and obda
the type is not materialised
after loading in triple store, same query
p,v
http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://www.w3.org/2002/07/owl#NamedIndividual 
http://data.vlaanderen.be/ns/adres#afgeleidVanGemeente,http://data.vlaanderen.be/id/gemeente/200002
http://data.vlaanderen.be/ns/adres#gemeenteNaam,Antwerpen
http://data.vlaanderen.be/ns/adres#gemeenteNaam,Antwerpen
http://data.vlaanderen.be/ns/adres#gemeenteNaam,Anvers
http://www.w3.org/2000/01/rdf-schema#label,Antwerpen

What can be the reason?

**Comment by skomlaebri** [comment]
Can you provide the log and output file of your materialization using the CLI?

**Comment by PaulZH** [comment]
The materialization can be found at http://mbx.cm/t/zd7gc.
I rerun the conversion now with logging configured to output to the file system now and update accordingly.

**Comment by PaulZH** [comment]
Log at http://mbx.cm/t/5c-El
At the end there was a com.microsoft.sqlserver.jdbc.SQLServerException: Operation timed out. But I think this should be giving enough input to start with.

**Comment by skomlaebri** [comment]
Thanks for reporting the problem. 
The issue appears during materialization with the command --separate-files. When a class has the same name of a property (only uppercase difference) the file with the triples from the class is overwritten by the file with the triples from the property. So in this case, the triples from http://data.vlaanderen.be/ns/adres#GemeenteNaam are overwritten by the triples of http://data.vlaanderen.be/ns/adres#gemeenteNaam. If you can modify your ontology, the easiest solution, until the bugfix, is to rename your properties. For example instead of http://example.org/address use http://example.org/hasAddress.

**Comment by PaulZH** [comment]
Many thanks.


I'll use the workaround for now.




  
  Kind Regards,



Paul Hermans



 

-------------------------



ProXML bvba

Linked Data services

KBO: http://data.kbodata.be/organisation/0476_068_080#id




(w) www.proxml.be




(e) paul@proxml.be




(tw)  @PaulZH



(t)  +32 15 23 00 76



(m) +32 473 66 03 20



 

 

Narcisweg 17



3140 Keerbergen



Belgium



 

ODEdu – Innovative Open Data Education and Training based on PBL
and Learning Analytics - http://odedu-project.eu/




OpenGovIntelligence  – Public Administration Modernization by
exploiting Linked Open Statistical Data  - http://www.opengovintelligence.eu
 



OpenCube – Linked Open Statistical Data - http://opencube-project.eu/

**Comment by skomlaebri** [comment]
Fixed in ae283d59ed0340f91f79cc84e7b2b805417a4713.
