### ISSUE TITLE
OWL 2 DL axioms restriction

### ISSUE THREAD

**Issue by CorentinK** [ontop/ontop#197]
Hello everyone,

I am a beginner in ontology development and ontop. My project consists in giving meaning to sensor data via the development of an ontology. Thus, I though that connecting my "urban sensor ontology" (based on the Semantic Sensor Network Ontology) to a database that receives sensor data with ontop, would be a great way to achieve that.

So far, everything worked fine, until I discovered that OWL 2 QL do not support certain axioms. I think I identified 5 types of axioms not supported in my case.

![owl 2 ql error](https://user-images.githubusercontent.com/29048168/27138079-9586ccf2-5117-11e7-8984-583c1d5553ae.jpg)

1. ???
2. ???
3. because MinCardinality isn't supported  ([https://www.w3.org/TR/owl2-profiles/#OWL_2_QL](url))
4. because  property chains aren't supported ([https://www.w3.org/TR/owl2-profiles/#OWL_2_QL](url))
5. because transitive properties aren't supported ([https://www.w3.org/TR/owl2-profiles/#OWL_2_QL](url))

In total, 620 axioms are not taken in consideration while running the ontop reasoner which is really problematic since I do need them and the relation they infer. Without them my ontology has no real reason of being.

Thus, I was wondering if there were some ways to overcome those issues? (additional plugin, axioms reformulation ...)

And do you think that in the futur such kind of limitation will be overcome?

Here is the entire log file:

[protegelog.txt](https://github.com/ontop/ontop/files/1075042/protegelog.txt)

Kind regards,

Corentin

**Comment by ghxiao** [comment]
Hi @CorentinK ,

We did some research on OBDA over expressive ontologies. The outcome is a proof-of-concept system Ontoprox https://github.com/ontop/ontoprox

    Ontoprox is a system for OBDA with expressive ontologies. 
    It rewrites OBDA specifications with an expressive ontology to “equivalent” ones 
    with a DL-LiteR ontology, if possible, and to approximate them otherwise.

Unfortunately, at this point, Ontoprox is not well-maintained because of lacking resources.

The idea behind Ontoprox is simple: simulating ontologies axioms with mappings. So what I can suggest to you now is to the same translation, but manually. 

Regarding the future future of Ontoprox, it is not clearly yet. In a perfect world I would like to reimplement it properly and put it in into the standard distribution of Ontop.
