### ISSUE TITLE
Does it include support for UDF (User Defined Function)

### ISSUE THREAD

**Issue by RaniRaven** [ontop/ontop#199]
Assume I would like to use a function, which is not ANSI SQL standard, is there a way to write it, in the mapping so that it'll be translated as is ?
Like substr for example (but with my own meaning).
I am merely interested in the reasoner part which translates to SQL

**Comment by skomlaebri** [comment]
Hi, User-defined function are not supported by ontop. If you insert your function (in a SQL query in  the target part of a mapping axiom), we will not be able to optimize your SQL query. We will treat your SQL query as a view and it will probably appear as a subquery in the final SQL translation of your SPARQL query.

**Comment by bcogrel** [comment]
As long as the UDF is already defined at the database level, it should normally work with Ontop.

The strategy for handling functions in our SQL parser has switched since 4.0. It now uses a blacklist, not a whitelist anymore. That is, only some particular functions are excluded. Unknown functions (not operators) should be preserved.

If someone still experiencing issues with UDFs, feel free to re-open this issue.
