### ISSUE TITLE
Problem with unfolding sparql query

### ISSUE THREAD

**Issue by Rani-Yaro** [ontop/ontop#200]
It seems that for every sparql which is a bit more complicated than 
select ?x where {?x a :Book}
The unfolding returns empty query. This behavior is consistent with that of the plugin for protege, although it seems like the query versus the jdbc driver is commited, or looks like it.

I can send the owl and the obda files, since it seems super wierd this behavior.
It seems by looking at the debug lines that the sparql is being parsed correctly, but for some reason the sql is empty.

Is there any explanation to that behavior ? It seems that the QuestReasoner should need nothing more but the mapping in order to create the sql query string, and yet through all the code examples it seems like it makes some use of the result-set of the jdbc connection in order to get some bindings which are part of the sql creation process in some way. Is there any explanation to that ?

**Comment by skomlaebri** [comment]
Hi,
send us the ontology mapping and query files, so we can have a look at the problem.

**Comment by jesushd12** [comment]
Hi, I think i'm getting the same behavior. 
I have a target
>  :hoteles{id} a :Hoteles ; :se_encuentra_en :Ciudad_Guayana . 
and a source 
> SELECT site.id
> FROM 
> base_city as city,
> base_poi_object as site,
> base_descriptor as bd, 
> base_level as concept
> WHERE 
> concept.name = 'Hoteles' AND
> bd.level_id = concept.id AND
> bd.poi_object_id = site.id AND
> city.id = 3 OR city.id = 4 AND
> site.city_id = city.id 

The test with  jdbc driver works fine and I get the correct data, but when I make this query through Ontop Sparql
SELECT DISTINCT ?subject  
	WHERE { ?subject a mon:Hoteles; mon:se_encuentra_en mon:Ciudad_Guayana}
I don't get any results

Grettings.

**Comment by skomlaebri** [comment]
Hi,
I can see that in the mappings you are using : as a prefix and for the SPARQL query you are using mon: as prefix .
Are the two prefixes you are using the same?

If yes, can you provide the [log file](https://github.com/ontop/ontop/wiki/BugReport#how-to-generate-the-log-file)?

**Comment by jesushd12** [comment]
Hi, I'm following the instruction to generate the .log  but it tells me: showFile not implemented for Linux when I click "Show Log file"

**Comment by skomlaebri** [comment]
Hi, one you set the log file to debug, it's also enough if you restart protege and send us the output in your terminal (after having executed your SPARQL query).

**Comment by jesushd12** [comment]
When I run the SPARQL query: 
SELECT DISTINCT ?subject
WHERE { ?subject a mon:Hoteles; mon:se_encuentra_en mon:Ciudad_Guayana}
I get this
--------------------------- Ontology Sources Manager --------------------------- 
Checking to see if ontology document has changed. 
    Ontology: OntologyID(OntologyIRI(<http://localhost/ontologias/OntologiaMomentosV3>) VersionIRI(<null>)) 
    Document: file:/home/jesus/Documentos/protege/ontologias/Reusing/tourismV5.owl 
    Last modified in Protege: 1500396560000 
    Last modified externally: 1500396560000 
    Ontology document has not changed externally 
 
Executing SPARQL query: 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mon:<http://localhost/ontologias/OntologiaMomentosV3#>
SELECT DISTINCT ?subject  
	WHERE { ?subject a mon:Hoteles; mon:se_encuentra_en mon:Ciudad_Guayana}

 
Executing the SQL query and get the result... 
Execution finished.

-------------------------------------------------------------------------------------------
Now, I tried with my previous queries like
SELECT DISTINCT ?subject  
	WHERE { ?subject a mon:Hoteles} it worked before but i'm getting :

it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
Unbound variable found in WHERE clause: p2_55_300 
it.unibz.inf.ontop.owlapi.OntopOWLException: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
Unbound variable found in WHERE clause: p2_55_300
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:110) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:194) ~[na:na]
	at it.unibz.inf.ontop.protege.views.QueryInterfaceView$2.executeQuery(QueryInterfaceView.java:161) ~[na:na]
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction$1.run(OBDADataQueryAction.java:152) ~[na:na]
Caused by: it.unibz.inf.ontop.model.OBDAException: Error rewriting and unfolding into SQL
Unbound variable found in WHERE clause: p2_55_300
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getSQLString(SQLGenerator.java:1261) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getSQLString(SQLGenerator.java:1307) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getSQLString(SQLGenerator.java:1306) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getSQLCondition(SQLGenerator.java:364) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getBooleanConditionsString(SQLGenerator.java:306) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getConditionsString(SQLGenerator.java:566) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.getWHERE(SQLGenerator.java:718) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.generateQuery(SQLGenerator.java:269) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.sql.SQLGenerator.generateSourceQuery(SQLGenerator.java:168) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestQueryProcessor.getSQL(QuestQueryProcessor.java:226) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.startExecute(QuestStatement.java:354) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.executeTupleQuery(QuestStatement.java:318) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.core.QuestStatement.execute(QuestStatement.java:222) ~[na:na]
	at it.unibz.inf.ontop.owlrefplatform.owlapi.QuestOWLStatement.executeTuple(QuestOWLStatement.java:104) ~[na:na]
	... 3 common frames omitted

Could debug mode have some errors?

**Comment by jesushd12** [comment]
Edit: The second error doesn't appear (My queries worked again). But, the first one keeps occurring.

**Comment by RaniRaven** [comment]
ok,
I think that jesushd12 met some other problems, and it seems like the sparql query he presents is somewhat weird, which might suggest the problem.
However, mine is different 
[test - Copy.owl.txt](https://github.com/ontop/ontop/files/1158565/test.-.Copy.owl.txt)
[test - Copy.obda.txt](https://github.com/ontop/ontop/files/1158566/test.-.Copy.obda.txt)
I've attached the files and now the query 
PREFIX : <http://unit.hamama/test#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select distinct ?p1
WHERE {
   ?id :memberIn ?org.
   ?org rdf:type :organization_name.
   ?id :owns ?p1.
   ?id rdf:type :identification.
   ?p1 rdf:type :msisdn.
   FILTER (?org = "yyy")
}
It returns nothing when converted to sql 

The debug logs do show that it is parsed correctly, and no idea why no error, just empty sql.
The query is not so complicated,

**Comment by skomlaebri** [comment]
Hi @RaniRaven are you using ontop 1.18.1? We solved recently a problem in the use of filter with IRI. If updating ontop version does not solve the issue, can you share with us the complete debug log?

**Comment by RaniRaven** [comment]
I am indeed working with the last version.
The debug log is attached
[ontop_debug_log.txt](https://github.com/ontop/ontop/files/1158743/ontop_debug_log.txt)
I can also send you the code, I took the example code and converted it to work with the last version.
BTW, you may check it with any available version you've, as you have now everything, both the files and the query

**Comment by skomlaebri** [comment]
Hi,
I thought the query you sent us was just a  sample query  and you were substituting "YYY" with some other values.
The system is not returning any SQL translation because it understood that this query will not have any results. This happens because  :memberIn is declared in your ontology and mapping as an object property, if you try to filter the result comparing with  a literal value (in your case "YYY") it will always give empty result. You can try to run something as:

 select distinct ?p1
WHERE {
?id :memberIn ?org.
?org rdf:type :organization_name.
?id :owns ?p1.
?id rdf:type :identification.
?p1 rdf:type :msisdn.
FILTER (?org = <http://unit.hamama/test#organization_name-YYY>)
}

**Comment by RaniRaven** [comment]
I probably miss some substantial issue there.
I am trying to use this system in order to translate sparql to sql, in order to run the sparql queries over an RDB (or jdbc exposed data source).
If the system is querying the data source, and only then producing the sql query, why do I need the query, if I can get the results directly.
I am probably missing something technical here, but to my understanding there should be no need of looking at the data in order to produce the SQL translation of the SPARQL.
Is there any way to get the best optimized SQL query, without having any result at the local store connected ?

**Comment by RaniRaven** [comment]
Assume I wish only to translate sparql to sql as efficient as possible based on the meta-data (fields, indices, constraints only).

**Comment by skomlaebri** [comment]
Hi,
ontop has not been projected with the purpose of translating SPARQL query to SQL query, but only to provide the answer to the SPARQL query. 
So if the solution can be inferred already from the mapping and ontology the SQL translation is not done. 
Ontop is looking at the  information you have provided with the ontology and mapping. 
In your specific case: You declared in the ontology :memberIn as an object property, so it is clear without looking at the data in your database that there is no solution for your query in which you ask to filter based on a literal (:memberIn should have been a datatype property to get an answer).
