### ISSUE TITLE
Entailment regime, OWL 2 Profile and SPARQL 1.0

### ISSUE THREAD

**Issue by CorentinK** [ontop/ontop#205]
Hi,

I have a question about the SPARQL Query language and the entailment regime used?

I found in the wiki that ontop was based on a SPARQL engine (SPARQL 1.0) that supports RDFS and OWL 2 QL entailment regimes.  However, I read that entailment regimes were introduced with SPARQL1.1. So I am a bit confused on the query language that is being used in ontop?

Moreover, I read that OWL 2 QL was a  OWL 2 profile whereas in the wiki it is considered as a entailment regime. Could you explicit the difference?

Many thanks in advance for your help,

Corentin

**Comment by ghxiao** [comment]
Dear Corentin,

Sorry for the late reply. Just came back from vocation.
This is a very good but non-trivial question. Let me try to explain.

Currently Ontop supports almost all the features of SPARQL 1.0, and some of the new features of SPARQL 1.1. The full support of SPARQL 1.1 is our ongoing  effort.

OWL 2 QL itself is an ontology language, or more precisely an OWL 2 profile. 

SPARQL 1.0 only defined how to query RDF graphs, which means all the reasoning capabilities from OWL cannot be used with SPARQL 1.0. To solve this issue, the entailment regime introduced by SPARQL 1.1 defines how to view an OWL ontology as an (entailed) RDF graph in order to be queried by SPARQL. The entailed graph contains not only axioms explicitly declared in the ontology, but also axioms entailed by the ontology. OWL 2 QL entailment regime says that one can view an OWL 2 QL ontology as an RDF graph, including all the axioms entailed by the ontology following OWL 2 QL reasoning. Ontop supports (most of) the OWL 2 QL entailment regime.

I hope this clarified your confusion. Please let us know if there is anything unclear.

Cheers,

Guohui
