### ISSUE TITLE
In DIVIDE(value1,value2): Incompatible type inferred : expected: null, actual: LITERAL

### ISSUE THREAD

**Issue by CorentinK** [ontop/ontop#210]
Hi,

I am trying to divide 2 variables expressed as xsd:decimal.

I have this error when running the following query:

> ERROR OBDADataQueryAction    it.unibz.inf.ontop.exception.OntopTypingException: In DIVIDE(value1,value2): Incompatible type inferred : expected: null, actual: LITERAL

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX usa: <http://www.semanticweb.org/corentin/ontologies/2016/11/urban_sustainability_assessment#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT (?value1/?value2 AS ?result) WHERE{

#first query
{
SELECT ?value1 WHERE{

?ob a ssn:Observation ; ssn:observationSamplingTime ?time ; ssn:observationResult ?so; ssn:observedProperty ?op; ssn:featureOfInterest ?foi.
?op rdf:type usa:EnergyProperty.
?foi rdf:type usa:TotalEnergyDemand.

?time a usa:SamplingStartTime ; dul:hasRegionDataValue "2014-07-25T01:00:00.0"^^xsd:dateTime .
?obsva  dul:isRegionFor ?so ; dul:hasRegionDataValue ?value1.   

}
}

#second query
{
SELECT ?value2 WHERE{

?ob a ssn:Observation ; ssn:observationSamplingTime ?time ; ssn:observationResult ?so; ssn:observedProperty ?op; ssn:featureOfInterest ?foi.
?op rdf:type usa:EnergyProperty.
?foi rdf:type usa:TotalEnergyDemand.

?time a usa:SamplingStartTime ; dul:hasRegionDataValue "2015-03-31T01:00:00.0"^^xsd:dateTime .
?obsva  dul:isRegionFor ?so ; dul:hasRegionDataValue ?value2.   

}
}
}
```

Where is my mistake?

PS: the ERROR is the same for all operators (ADD, MULTIPLY, DIVIDE...).

Find attached the log file.
[protege.log](https://github.com/ontop/ontop/files/1348704/protege.log)

Best regards,

CorentinK

**Comment by bcogrel** [comment]
Hi CorentinK,

Thanks for reporting the issue.

### Explanation

According to your mapping assertions, ?value2 is sometimes a boolean, which is, according to the SPARQL specification, not a numeric value. Therefore using a boolean value with a numeric operator must produce a "SPARQL error". 

By contrast with SQL, SPARQL is robust to this kind of error: when occurring in a assignment (BIND), the value is unbound, when occurring in a FILTER expression, then latter is most of the time interpreted as effectively false.

So it means that, according to the specification, your query is valid and should thus not be rejected. When ?value is boolean,  ?result should simply be unbound.

However, the current implementation of Ontop 3.0 is not yet robust to SPARQL errors: it detects them but throws an exception instead of handling them smoothly. 

### Solutions

We are planning to make Ontop robust to SPARQL errors, but this will not be achieved for Ontop 3.0 since it requires a substantial effort.

For the beta 2, we plan to support the isNumeric function, which would allow you to filter out boolean values. We will also make the message of the exception more explicit.

The current workaround we propose you is to use two different properties for boolean and numeric values.

Best,
Benjamin

**Comment by CorentinK** [comment]
Hi Benjamin,

I have done as you suggested and created a data property hasNumericValue that concerns numeric value only.

The issue seems to be solve but I have now a new error message:

> it.unibz.inf.ontop.exception.OntopTranslationException: java.lang.RuntimeException: Unexpected function in the query: DIVIDE

Find the log attatched. 
[protege.log](https://github.com/ontop/ontop/files/1356254/protege.log)



 I have tried simpler query like:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX usa: <http://www.semanticweb.org/corentin/ontologies/2016/11/urban_sustainability_assessment#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>

SELECT (?value1/10 AS ?result) WHERE{

?obsva usa:hasNumericValue ?value1.

}
```
 The result is the same. 
[log2.txt](https://github.com/ontop/ontop/files/1356286/log2.txt)


Note that ontop 1.18.1 can solved this simple query but unfortunatelly cannot solve my initial query (running forever).

Thanks for your help,

Best,

Corentin
