### ISSUE TITLE
Question: Importing IMDBOBDA database data  into movieontology

### ISSUE THREAD

**Issue by karanthpallavi** [ontop/ontop#259]
Hello,

Have tried using Ontop protege plugin, i give connection parameters to import movie data from postgresql database,
Connection is established,
How do i get complete data from database into ontology and save it as ontology?
Kindly help,
Thanks in advance

**Comment by juliencorman** [comment]
Hello,

Did you try "Ontop/Materialize triples"?

**Comment by juliencorman** [comment]
Hello,

I you are wondering why the values of some columns are not extracted, this is the expected behavior.
Materialization is based on the mapping (the .obda file): for each mapping assertion, the source SQL query is executed over the database, and the target of the mapping assertion dictates which RDF triples are generated.
So feel free to edit the .obda file according to your specific needs.

Alternatively, you may want to try the (experimental) Ontop bootstrap feature: 
http://github.com/ontop/ontop/wiki/OntopCLI#ontop-bootstrap
This will automatically generate a different mapping (.obda) and ontology (.owl) for your database, based on the column names.
Then you can materialize as before.

Another tip: for additional materialization options, you can use the command-line interface instead of Protege:
http://github.com/ontop/ontop/wiki/OntopCLI#ontop-materialize
  
Regards,
Julien

**Comment by karanthpallavi** [comment]
Thats a detailed answer, Thanks much, will try using bootstrap..
