### ISSUE TITLE
How to split retrieval and querying by intermediately persisting the R2RML mapped triples?

### ISSUE THREAD

**Issue by JensPiegsa** [ontop/ontop#267]
Hi,

I successfully used the Java API of Ontop to pull data from a relational database and make it available through R2RML, OWL and SPARQL. For performance and validation reasons, I now like to split retrieval and querying by intermediately persisting the mapped triples. Is there any Ontop 3 example code illustrating the two steps:

1. How to persist all triples resulting from an R2RML mapping (maybe in a RDB).
2. How to instantiate a reasoner based on the persisted triples.

Regards,
Jens

**Comment by juliencorman** [comment]
Hello Jens,

You can use Ontop to materialize the graph induced by your r2rml mapping (and ontology).
This is documented here: http://github.com/ontop/ontop/wiki/OntopCLI#ontop-materialize 
As a Java entry point, you may try it.unibz.inf.ontop.cli.OntopMaterializeTest.

Then you can feed this data to an OWL reasoner or a triplestore, depending on your needs.

Regards,
Julien

**Comment by bcogrel** [comment]
Hello Jens,

I don't have a very clear understanding about what you want to do and what your motivations are, but perhaps some explanations about the "mission" of Ontop v3 could help.

Ontop v3 is specialized on querying/materializing virtual RDF graphs stored in a DB and requires for this purpose an RDF-to-DB mapping. So in theory, nothing prevents you from storing triples in a "generic triple table" in a relational DB and write a single mapping assertion for populating the virtual RDF graph. However, I doubt it is a good idea because Ontop would generate very inefficient SQL queries since there is basically no structure that can be used for optimizing.

So if you want to materialize your RDF graph and then query it, I would suggest you to load it into a regular triplestore (e.g. Virtuoso). Note that when you provide an ontology, the Ontop materializer already performs some reasoning and materializes what we call the saturated RDF graph, that is the graph you obtain after applying to the user-provided mapping all the domain, range, subClassOf, subPropertyOf and inversePropertyOf rules coming from the ontology.  Therefore most of the reasoning Ontop can do (expect existential reasoning, but this is an advanced topic and this feature is disabled by default) is already applied during materialization, so reusing Ontop above the materialized saturated graph would usually not bring anything more in terms of reasoning.

Regarding the semantic index module you mentioned, it is now only used for test purposes (basically for running the official SPARQL compliance tests) and is not targeted for end-users. Ontop v3 do not provide a "classic ABox mode" anymore like in 1.x versions. Our plan is to keep the semantic index as minimal as possible (we already simplified it and better aligned it with the "virtual mode") and perhaps remove it if its maintenance becomes a problem at some point.

Best,
Benjamin

**Comment by JensPiegsa** [comment]
Hello Benjamin,

thanks for your clarification about the current scope of Ontop. So let me summarize how this applies to our use case.

In our application, we have two types of data sources:

I. Data sources that are queried for *all* their data to populate a singleton in-memory model at application startup. This model instance is used to display a browsable catalogue to our users. That's where a front-up materialization and a later "classic mode" querying would make sense.

II. Data sources that are queried on a per-request basis for just a small portion of their data. That's where the "virtual mode" is used.

To deal with both types, I now see two options:

A. setup a native triple store for type (I) and query it through another API (Apache Jena?) and stay with Ontop for type (II).

B. fake "classic mode" with a "generic triple table" + single R2RML assertion with the downside of not gaining much performance compared to the "virtual mode" (varying by the complexity of the R2RML mapping).

For a variation of (A) — as it doesn't feel right to have multiple SPARQL APIs in the same application — I wonder whether Ontop is able to publish a SPARQL endpoint and how to query both types of data sources through the same API.

Cordially,
Jens

**Comment by juliencorman** [comment]
Hello Jens,

(A) clearly seems like the better option.

As for the API, this is not really an issue: Ontop already complies with the RDF4J API, and you can use it as well to query a triple store (e.g. Virtuoso: http://vos.openlinksw.com/owiki/wiki/VOS/VirtSesame2HttpRepository)

Alternatively, if you want to expose both datasets as a unique SPARQL endpoint, you may deploy a SPARQL federator (such as Semagrow) on top of Ontop and the triple store, but this could be more advanced.
 
Regards,
Benjamin and Julien

**Comment by JensPiegsa** [comment]
Dear colleagues,

Thanks for these tips. I close this issue now.  Keep up the great work!

Regards,
Jens
