### ISSUE TITLE
Can protege connect to any other data federation tools except teiid?

### ISSUE THREAD

**Issue by xxs7130** [ontop/ontop#276]
### Description

Teiid will not update teiid with eclipse. I tried to use the standalone.bat and jboss-cli.bat to deploy a VDB, but there are many mistakes that I can't resolve. If there is another data federation tools that I can use in Protege to finish the bookFederation example?

**Comment by bcogrel** [comment]
Hi,
On the open-source side, since 3.0.0-beta2, we have started to support Dremio. If Dremio is easy to use, it unfortunately does not provide schema metadata (e.g. primary and foreign keys) which is needed by Ontop to optimize the queries. This means that one has to declare the schema constraints manually in a separate file (see https://github.com/ontop/ontop/wiki/Implicit-database-constraints).

Support for the commercial system Denodo is available in the current `version3` branch and will be included in the upcoming 3.0.0-beta3. Denodo provides schema metadata and so far seems to interact nicely with Ontop. You can give a try to the Express edition of Denodo, it is available for free but has some usage restrictions.

Best,
Benjamin

**Comment by ghxiao** [comment]
Hi, we have created a tutorial with data federation tools Dremio and Denodo. 
https://github.com/ontop/ontop-tutorial/tree/master/federation

Now I close the issue, but feel free to reopen it if you have other issues.
