### ISSUE TITLE
Decouple ontop-protégé from the Ontop code base 

### ISSUE THREAD

**Issue by bcogrel** [ontop/ontop#278]
Currently, ontop-protégé depends not only on Protégé (as a plugin) but also on ontop-owlapi and transitively on most of the Ontop modules.

The goal here is break this dependency and let most of the Ontop modules evolve independently of the constraints brought by Protégé (e.g. Java, OWLAPI and Guice versions). 

This will be achieved by limiting the interaction between ontop-protégé and other Ontop modules to SPARQL-HTTP and the CLI.

**Comment by ghxiao** [comment]
This issue tracks a major ongoing refactoring for the code relevant to the protege plugin. Instead of using HTTP protocol, which requires too much development work, we seek an alternative solution using Maven and shading techniques.

,The protege plugin was a normal submodule of the code base. Since several dependencies of protege are pretty old (e.g., `owlapi` and `guava`), this brings significant challenges for upgrading these libraries for Ontop. (see https://github.com/ontop/ontop/issues/498, https://github.com/protegeproject/protege/issues/1072)

Objectives:
- Core ontop depends on the latest version of libraries
- Protege plugin continues to work, which means it depends on several older libraries
- IDE friendly. The modified code with shading will still be recognized by IntelliJ IDEA

It happens in the branch `feature/protege-decouple`: https://github.com/ontop/ontop/commits/feature/protege-decouple

The solution is essentially a modified version of option `(A) shading with additional module ontop-protege-dependencies` discussed in https://github.com/ontop/ontop/issues/467#issuecomment-920108155.  

 More in detail:
- We move the protege-relevant code to the `protege` directory. From there, we create a module called `ontop-protege-parent`. Notably, `ontop-protege-parent` is *NOT* a submodule of ontop. 
- `ontop-protege-parent` has two submodules `ontop-protege-dependencies` and `ontop-protege-plugin`
- `ontop-protege-dependencies` repacks the ontop jars and dependencies as a single shaded fat jar. Currently, only the Guava classes are shaded
- `ontop-protege-plugin` depends on `ontop-protege-dependencies`.
