### ISSUE TITLE
SQL_GENERATE_REPLACE for version 3 ?

### ISSUE THREAD

**Issue by seralf** [ontop/ontop#312]
### Description

It would be useful to have a way to disable the usage of SQL `REPLACE(...)`: the replacements could be generated directly in java before sending the actual query.

There were a configuration option I used with version 1.18 to avoid this behaviour: (`QuestPreferences.SQL_GENERATE_REPLACE=false`).
But looking at version 3 code, it seems that there is no way to control this:
https://github.com/ontop/ontop/blob/version3/engine/reformulation/sql/src/main/java/it/unibz/inf/ontop/answering/reformulation/generation/dialect/impl/SQL99DialectAdapter.java#L42-L56

Are there ant way to avoid the `REPLACE`, or any plan to add the option to disable them in version 3 too?

Some character in the URI is replaced using SQL `REPLACE(...)` function, rather than an equivalent one in java

### Steps to Reproduce
execute a query with an URI template containing special chars

**Expected behavior:** 
generate an SQL without the REPLACE() function

**Actual behavior:**
the generated SQL query contains a sequence of nested REPLACE(...) statement

**Reproduces how often:**
it happens all the time

### Versions

Version 3

### Additional Information

For version 1.18 there were a `QuestPreferences.SQL_GENERATE_REPLACE` option

**Comment by ghxiao** [comment]
Hi,

In version3, you can put the following line into the properties file, which contains the info of JDBC connection:
```
ontop.iriSafeEncoding=false
```

Note that in the forthcoming 4.0 version, IRI generation will be done at the Java level as a postprocessing step as much as possible, so this option will likely not be needed anymore in the future.

**Comment by seralf** [comment]
Hi Guohui 
it works as expected, thanks! :-)

**Comment by GeorgFerdinandSchneider** [comment]
Dear @ghxiao, team,

We observe this behaviour (Multiple REPLACEs occuring in SQL Statement) in Ontop 4.2.

Our setup:

- Connect via JDBC to Denodo 8 using {jar](https://community.denodo.com/drivers/jdbc/8.0)
- GraphDB 10.1.1/ Ontop 4.2 and Ontop 4.2 standalone from local PC

We see the nested REPLACEs both when using Ontop from GraphDB as well as Ontop standalone.

We were wondering if there is some leftover cases where ontop adds the nested REPLACES, e.g. when connected via "generic JDBC Driver" connections?

Best

Georg

**Comment by VladimirAlexiev** [comment]
I see the same `REPLACE(REPLACE(REPLACE...` in:
- https://github.com/ontop/ontop/issues/363 (with v3.0.1)
- https://github.com/ontop/ontop/pull/577 (slated for v5.0) with `ontop.reformulateToFullNativeQuery`
- https://github.com/ontop/ontop/issues/202 (closed in 2018 because of inactivity) 

@bcogrel @ghxiao This sequence of replaces makes the queries twice slower in many cases,
Could you make it the default that NO such replacements are generated?

**Comment by bcogrel** [comment]
Hi @GeorgFerdinandSchneider and @VladimirAlexiev,

Thank you for raising the performance issues you experienced.

This large nesting of REPLACEs is our translation in SQL of [R2RML's IRI safe-encoding](https://www.w3.org/TR/r2rml/#dfn-iri-safe). We try to avoid including it in SQL queries as much as possible by following optimizations:
  - Decomposing the IRI templates so as to join over its components rather over the IRI template strings. For that, we need to make sure the IRI template is injective if it takes more than one argument. Since https://github.com/ontop/ontop/issues/363, we take into account the argument's data types to detect more cases of injectivity.
  - Eliminating them for data types that do not need to be safely encoded (e.g. integers or UUIDs). See [`DBTermType.isNeedingIRISafeEncoding()`](https://github.com/ontop/ontop/blob/version5/core/model/src/main/java/it/unibz/inf/ontop/model/type/DBTermType.java#L21).
  - Post-processing IRI templates: IRI strings are then built after retrieving the SQL results. This is done when the IRI template string can be lifted outside the SQL query and when no more than `ontop.maxNbChildrenLiftingDBFS` (by default 10) different IRI templates are possible for the same variable.

Could you please tell us a bit more about your settings? In particular:
  - Are you using Ontop for materializing the RDF graph or in the virtual setting?
  - What are the data types of the IRI template arguments? Arbitrary strings or data types with limited lexical spaces?

In some cases the problem can be simply handled by better modelling some data types for a particular SQL dialect.

Re-introducing an option for disabling R2RML's IRI safe-encoding could be done, by this should be treated as a "hack" that is not very safe to use, because:
  - It violates the R2RML standard and may return different results
  - It can produce invalid IRIs (for instance including spaces)
  - Querying the virtual graph may return less results than querying the materialized graph because the template is not injective anymore when safe-encoding is disabled
  - It is a global setting, which might solve the performance issue for a particular IRI template but create issues for others.

Best,
Benjamin

NB: The feature introduced by https://github.com/ontop/ontop/pull/577 makes the REPLACEs appear more frequently in  SQL queries when enabled, as it disables post-processing.

**Comment by VladimirAlexiev** [comment]
@GeorgFerdinandSchneider reports that:
- Query performance with REPLACE is 60% slower (68s vs 26s).
- The columns being substituted in the URL template are `SystemID, SchemaID, DimensionName, CubeName`, and I guess all of them are string
- (The columns are used quoted like this `{\"SystemID\"}`, but I assume this cannot cause the REPLACE)

@bcogrel Indeed the spec you quote says:
> R2RML **always** performs percent-encoding when IRIs are generated from string **templates**. If IRIs need to be generated **without percent-encoding**, then **rr:column** should be used instead of rr:template, with an [R2RML view](https://www.w3.org/TR/r2rml/#dfn-r2rml-view) that performs the string concatenation.

The way I read this:
- `rr:column "SystemID"` is assumed to be URL-safe
- `rr:template "https://example.com/{SystemID}"` is assumed to be URL-unsafe
- the spec suggests to make a view like `select concat("https://example.com/",SystemID) as SystemID_URL` and then use that column

The philosophy of R2RML is that any needed data transformation is done in SQL views, as you cannot do any data transformation in the mapping (there are no functions).
- So IMHO it should be up to the SQL database designer to ensure that columns used in URL templates are URL-safe.
- ONTOP takes over this responsibility by doing the multiple REPLACEs, resulting in much worse query performance
- Furthermore, percent escaping results in ugly URLs such as `http://data.example.com/site/NEW%20YORK`. In our KG building projects we use a function `urlify()` that replaces any punctuation chars with a single underscore and removes leading/trailing punctuation. So eg `Schenectady (New York)` results in a URL fragment `Schenectady_New_York`, which is much better than a fragment with 4 percent-encoded chars `Schenectady%20%28New%20York%29`

The approach taken in the spec seems like a missed opportunity to me:
- If columns alone are assumed to be URL-safe, why columns inside templates are assumed to be URL-unsafe?
- Note: the fixed parts of the template are not percent encoded (they must be left alone by definition)

I think ONTOP should explore two avenues to amend the situation:
- Options to declare specific columns of tables or views to be URL-safe, so they are not subjected to percent encoding
- Some way to do the percent encoding faster (using one operation). Maybe with database-specific UDFs (I'm no database expert). Eg in Perl I can do it with a single regex like this, where `e` causes evaluation, and the char class `[...]` needs to extended with more URL-unsafe chars:
  `s{([% /()])}{"%".sprintf("%X",ord($1))}eg`

Testing:
```
perl -we '$_="Schenectady (New York)"; s{([% /()])}{"%".sprintf("%X",ord($1))}eg; print'
Schenectady%20%28New%20York%29
```

> the template is not injective anymore when safe-encoding is disabled

I think if someone uses templates without delimiters (eg `base/{foo}{bar}`), or the delimiters may appear inside columns, they are calling for trouble.
By striving to save such bad users, ONTOP makes it hard or impossible for good users to have good-performance queries.

Cheers!

**Comment by GeorgFerdinandSchneider** [comment]
Dear @bcogrel and @VladimirAlexiev,

adding to @VladimirAlexiev 

> * The columns being substituted in the URL template are SystemID, SchemaID, DimensionName, CubeName, and I guess all of them are string


Indeed all inputs to the template are character strings according to [Denodo´s definition](https://community.denodo.com/docs/html/browse/latest/en/vdp/vql/language_for_defining_and_processing_data_vql/data_types/data_types)

> * A. Options to declare specific columns of tables or views to be URL-safe, so they are not subjected to percent encoding

This would be indeed a solution approach I would be happy to support

Best

Georg

**Comment by bcogrel** [comment]
Dear @GeorgFerdinandSchneider and @VladimirAlexiev,

Thank you for this rich feedback from the materialization side of Ontop.

In the R2RML spec, yes, `rr:column` is the mechanism to use when you want to have full control over the IRI construction. `rr:template` instead produce a robust and "virtualization-friendly" mechanism to build IRIs from arbitrary DB values.

Note that R2RML does not percent-encode certain characters like `_`, `.` and `-`, as they are part of the [`iunreserved` production rule](https://www.rfc-editor.org/rfc/rfc3987#section-2.2).

I like the option A idea. We could let users specify this kind of "constraint" in [`lenses`](https://ontop-vkg.org/guide/advanced/lenses), as we already do for non-nullability and functional dependencies. I will open an issue for that.

Option B is definitely challenging and is expected to be quite intrusive, in particular because one usually needs special rights for creating UDFs. But any dialect-specific improvement on that side is worth considering.

A third option would be to find a way to make the SPARQL queries less generic, so as to maximize the chance for the IRI templates to be post-processed (in Java). For example, if we materialize all the instances of a particular class at one time,  the number of IRI templates per variable might be small enough.

Option A still sounds the best to me.

Best,
Benjamin
