### ISSUE TITLE
Casting errors when running Ontop with Teiid and MySQL

### ISSUE THREAD

**Issue by thomas-delva** [ontop/ontop#327]
### Description
When using Ontop+Teiid over MySQL, for some SPARQL queries, Ontop generates a SQL query for which Teiid gives errors.

### Steps to reproduce
(Detailed steps and commands can be found in the attached `bsbm_install.txt` for step 1. and in `teiid_install.txt` for steps 2. and 3.)
1. Load data into a MySQL and a Mongodb instance.
2. Configure Teiid to integrate those two databases and then run Teiid.
3. Execute a SPARQL query with Ontop over Teiid.

**Expected behaviour:** Teiid executes the SQL query generated by Ontop, by sending queries to the MySQL and MongoDB databases.

**Actual behaviour:** MySQL can not parse the SQL query which it receives from Teiid. 

In particular, MySQL responds with: `Caused by: java.sql.SQLSyntaxErrorException: Remote java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''), ']', '%5D'), '^', '%5E'), '\`', '%60'), '{', '%7B'), '|', '%7C'), '}', '%7D')' at line 1`.

**Reproduces how often:** Reproduces always for certain queries. We assume it happens for those queries where an IRI template is filled in with a non-string value (e.g. an integer).

### Attached material
[bsbm_install.txt](https://github.com/ontop/ontop/files/4280614/bsbm_install.txt)

[teiid_install.zip](https://github.com/ontop/ontop/files/4280624/teiid_install.zip) (contains installation steps for Teiid, as well as mapping and config files for Ontop)

[query5.txt](https://github.com/ontop/ontop/files/4280630/query5.txt)

[query5.log](https://github.com/ontop/ontop/files/4280610/query5.log)

### Versions
ontop version 3.0.1

mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

mysql-connector-java-8.0.19

teiid-13.0.2

### Additional notes
Some investigation into the errors leads us to believe that their cause is the casting of integers to characters when making IRIs from templates. 

This excerpt from the query Ontop sends to Teiid:
`('http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer' || REPLACE( ... REPLACE(CAST("Qmysql_productVIEW0"."producer" AS VARCHAR), '%', '%25'), ... '}', '%7D') || '/Product' || REPLACE( ... REPLACE(CAST("Qmysql_productVIEW0"."nr" AS VARCHAR), '%', '%25'), ... '}', '%7D')) AS "product"`

Is translated into this SQL fragment of the query Teiid sends to MySQL:
`concat(concat(concat('http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer', replace( ... replace(cast(g_6.producer AS char), '%', '%25'), ... '}', '%7D')), '/Product'), replace( ... replace(cast(g_6.nr AS char), '%', '%25'), ... '}', '%7D')) AS c_2`

However, it can be verified that MySQL does not support this last syntax for casting, by e.g. trying the query: `SELECT concat('http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer', g_6.producer AS char) from product as g_6;`

**Comment by juliencorman** [comment]
Hello Thomas,

Thank you for the feedback.

First, I suspect a typo in the last query that you provided (which may explain why MySQL cannot parse it).
In `SELECT concat('http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer', g_6.producer AS char)`
I guess `cast` should be used instead of `concat`.

Now about the problem that you raised.
Ontop provides to Teiid a query that should be compliant with the SQL99 standard, and then Teiid is in charge of converting this query to specific dialects.
This means that our margin to modify the generated query is limited (by the SQL99 standard).

So if the query generated by Ontop in correct, a more robust solution would be to fix the conversion performed by Teiid.

That being said, in your specific case, you may try to deactivate Ontop's 'iriSafeEncoding' option, as illustrated here:
https://github.com/ontop/ontop/issues/312

Note also that in forthcoming versions of Ontop, the generation of IRIs from DB values will be post-processed (whenever possible), rather than delegated to the source engine.
This means that most 'replace' and 'concat' will disappear from the generated query. 

Best regards,
Julien

**Comment by thomas-delva** [comment]
Hi,

Thank you for the fast response!
I agree the issue is with the translation which happens in Teiid and not with Ontop.
That said, disabling IRI encoding fixed it for the queries I want to use.

Kind regards,
Thomas
