### ISSUE TITLE
Ontop materialize produces only triples

### ISSUE THREAD

**Issue by tpluscode** [ontop/ontop#343]
### Description

I am running `ontop materialize` to produce triples from an SQL Database. Unfortunately it appears to only output the default graph

It should also allow producing quad format. At least n-quads

### Steps to Reproduce

1. Use [`rr:graphMap`](https://rml.io/specs/rml/#named-graph) in R2RML mapping file
1. Run `ontop materialize`

**Expected behavior:** 

The output should be quads with correct named graphs

**Actual behavior:**

All maps which used `rr:graphMap` are ignored. The output only contains the default graph. Any subject/predicate map which produces quads are ignored

**Reproduces how often:** Always

### Versions

Ontop 4.0 RC1

**Comment by bcogrel** [comment]
Hi Tomasz,

Thanks for reporting this issue. 

Named graphs are supported since 4.0.0-rc1 at the mapping level and in the standard virtual setting, but not yet in the materialization one.

We need to update the materializer. At the moment, it performs CONSTRUCT queries targeting the default graph, hence the omission of the named graphs (https://github.com/ontop/ontop/blob/ontop-4.0.0-rc-1/engine/system/core/src/main/java/it/unibz/inf/ontop/materialization/impl/DefaultOntopRDFMaterializer.java#L62).

As CONSTRUCT queries can only return triples (not quads), we will have to change our strategy so as to issue one query for each pair of predicate (property or class) and named graph.

I did something similar for the RDB2RDF compliance tests: https://github.com/ontop/ontop/blob/ontop-4.0.0-rc-1/test/rdb2rdf-compliance/src/test/java/RDB2RDFTest.java#L416

@tirrolo is having a look at it.

Best,
Benjamin

**Comment by ghxiao** [comment]
Hi @tpluscode,

We have implemented materialization for quads and merged into the [releasing/v4.0](https://github.com/ontop/ontop/tree/releasing/v4.0) branch. 

Together with some minor bug fixes, we will make a minor release 4.0.1 out of it within this week.

**Comment by ghxiao** [comment]
Hi @tpluscode ,

This feature is now delivered as part of v4.0.1 release.
