### ISSUE TITLE
Ontop fails to execute the 6th query from BSBM benchmark (explore use case)

### ISSUE THREAD

**Issue by mchaloupka** [ontop/ontop#358]
### Description

Ontop fails to execute the 6th query from BSBM benchmark. For a sample query:
```
PREFIX rev: <http://purl.org/stuff/rev#>

DESCRIBE ?x
WHERE { <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Review195> rev:reviewer ?x }
```
It returns the following error:
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: Unknown column 'er10' in 'where clause'
```

### Steps to Reproduce
Checkout the following github https://github.com/mchaloupka/r2rml-benchmark and install prerequisities (see readme in the repository)

Start the interactive console:
```
dotnet fsi
```

Get the database and ontop running using the following command:
```
#load "benchmark.fsx"
Benchmark.generateData 20
open Database
open Docker
createNetwork benchmarkNetwork
startDatabaseContainer Databases.MySql
open Endpoints
ontopEndpoint.start Databases.MySql
;;
```

After that the Ontop is available at `http://localhost:5051/` and it is possible to try the query.

To stop everything that has been started, execute the following (in the interactive console):
```
Docker.stopAndRemoveContainer ontopEndpoint.dockerName
Docker.stopAndRemoveContainer databaseDockerName
removeNetwork benchmarkNetwork
#quit
;;
```

**Expected behavior:** The query should execute

**Actual behavior:** The query fails

**Reproduces how often:** Every time

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

It is run using the latest docker image `ontop/ontop-endpoint`, the actual command executed is the following:
```
docker run -d --name ontop-endpoint -v "/home/slupka/r2rml-benchmark/mapping:/benchmark/mapping" -v "/home/slupka/r2rml-benchmark/static:/benchmark/static" -v "/home/slupka/r2rml-benchmark/static/jdbc:/opt/ontop/jdbc" -e "ONTOP_MAPPING_FILE=/benchmark/mapping/mapping.ttl" -e "ONTOP_PROPERTIES_FILE=/benchmark/static/ontop.mysql.properties" -p 5051:8080 --net=benchmark-net ontop/ontop-endpoint
```

**Comment by ghxiao** [comment]
Thanks a lot for reporting this issue. Looks like a bug. I will look into it.

**Comment by ghxiao** [comment]
Hi,

This is actually an interesting bug.

Short story: `http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Reviewer10` is matching the IRI template `http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Reviewer{}` as expected, but also `http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/Review{}`. 
After decomposing the string, we were not checking it before converting into an integer, producing a DB integer with the lexical value `er10`. Because integers are serialized in SQL without quotes, it looked like a column.

This issue has now been fixed in the version4 branch already. You can already test it.

We are going to do a minor release 4.0.3 of Ontop in the next days with this fix and some small improvements.

**Comment by mchaloupka** [comment]
Thanks for letting me know. Please update this ticket when it will be released in docker, so I can retry it.

**Comment by ghxiao** [comment]
Hi @mchaloupka 

Ontop 4.0.3,  including the Docker image, has been just released. Please give it a try and let us know how it goes.

**Comment by ghxiao** [comment]
Hi, I close this issue. Please feel free to reopen it if the problem persists.

**Comment by mchaloupka** [comment]
I have tried it with the version 4.0.3 and it seems to be fixed.
