### ISSUE TITLE
Exception during translation for a query with spatial distance in SELECT and LIMIT

### ISSUE THREAD

**Issue by dbilid** [ontop/ontop#434]
### Description

An exception is thrown during query translation, when there exists a GeoSPARQL distance function in the SELECT clause, that involves two different base tables from the database, and also a LIMIT in the query. I am using PostGIS as the backend.

### Steps to Reproduce

1. create the following 2 tables in PostGIS:
`create table rivers (id integer, lat double precision, lon double precision);`
`create table lakes (id integer, lat double precision, lon double precision);`
2. create the classes River and Lake in the ontology and then the following 2 mapping assertions:
-Target:
`:rivers/{id} a :River ; geo:asWKT "<http://www.opengis.net/def/crs/EPSG/0/4326> {geometry}"^^geo:wktLiteral .`
-Source:
`SELECT id, ST_AsText(ST_SetSRID(ST_MakePoint(lon,lat),4326)) as geometry from rivers`
-Target:
`:lakes/{id} a :Lake ; geo:asWKT "<http://www.opengis.net/def/crs/EPSG/0/4326> {geometry}"^^geo:wktLiteral .`
-Source:
`SELECT id, ST_AsText(ST_SetSRID(ST_MakePoint(lon,lat),4326)) as geometry from lakes`

3. try to translate to SQL the query:
PREFIX : <http://www.example.com/example#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
SELECT ?dist WHERE {
?lake a :Lake ;
	geo:asWKT ?w1 .
?river a :River ;
	geo:asWKT ?w2 .
bind(geof:distance(?w1,?w2,uom:metre) as ?dist) .
} limit 1

**Actual behavior:** 
An exception is thrown with message: 
it.unibz.inf.ontop.exception.OntopReformulationException: it.unibz.inf.ontop.exception.MinorOntopInternalBugException: Was expecting a unique and known DB term type to be extracted for the SQL variable v1
at it.unibz.inf.ontop.owlapi.connection.impl.DefaultOntopOWLStatement.getExecutableQuery(DefaultOntopOWLStatement.java:205)
	at it.unibz.inf.ontop.protege.gui.action.OBDADataQueryAction.lambda$runAction$0(OBDADataQueryAction.java:152)
	at java.lang.Thread.run(Thread.java:748)

**Reproduces how often:**
It reproduces every time, but if I remove the triple pattern ?lake a :Lake or the triple pattern ?river a :River the query is translated. Also if I change the limit in some other number the query is translated,  but in some more complex setup, I keep getting this exception even with other limits.

### Versions

Ontop v4 commit 8ef4342692c1bf3edb2244e7b97486b5311645c4
PostgreSQL 12.7 with PostGIS  3.1

**Comment by ghxiao** [comment]
Hi @dbilid ,

I suspect that the problem is that Ontop is not able to do proper type inference about `ST_AsText(ST_SetSRID(ST_MakePoint`

Could try if the following simpler mappings work for you:

-Target:
`:rivers/{id} a :River ; geo:asWKT "<http://www.opengis.net/def/crs/EPSG/0/4326> POINT ({lon} {lat})"^^geo:wktLiteral .`
-Source:
`SELECT id, lon,lat as geometry from rivers`

-Target:
`:lakes/{id} a :Lake ; geo:asWKT "<http://www.opengis.net/def/crs/EPSG/0/4326> POINT ({lon} {lat})"^^geo:wktLiteral .`
-Source:
`SELECT id, lon,lat as geometry from lakes`

Btw, the SRID <http://www.opengis.net/def/crs/EPSG/0/4326> can be omitted in this example, because this is the default.

**Comment by ghxiao** [comment]
Another comment: although it is possible to construct a WKT literal in the mapping target, it is not recommended in production due to performance issue, because there is no spatial index over such values. One should add a separate column (e.g. called `geom` for the following example) for the geometry and add create a spatial index over it. In that case, the mapping can be as simple as:

- Target:
`:rivers/{id} a :River ; geo:asWKT "{wkt}"^^geo:wktLiteral .`
- Source:
`SELECT id,  ST_AsText(geom) as wkt from rivers`

**Comment by dbilid** [comment]
Hi @ghxiao,

indeed if I change the mapping, the query is translated, but unfortunately it seems that the translation contains invalid geometries. On the other hand, if I add geometry columns in both tables everything works fine. 

In case you want to see the invalid geometries that I mentioned, the produced query is the following:
SELECT ST_DISTANCESPHERE(CAST(v1."lat" AS TEXT),CAST(v2."lat" AS TEXT)) AS "v0"
FROM "lakes" v1, "rivers" v2
WHERE (v1."lat" IS NOT NULL AND v1."lon" IS NOT NULL AND v2."lat" IS NOT NULL AND v2."lon" IS NOT NULL)
LIMIT 1
