### ISSUE TITLE
Moving from ontologies to graphs as mean for expressing a unifying schema of sources

### ISSUE THREAD

**Issue by EdliraC** [ontop/ontop#536]
### Description

May I ask you for a question? Why Ontop moved from an ontology specification as unifying schema to a graph?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to see]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [Does it happen every time?]

### Attached material

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Which version of Ontop are you using and in which setting (Protege, SPARQL endpoint, Cli, Java API, ...)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by EdliraC** [comment]
Hello Benjamin,
I apologize for lack of good explanation for my question.
Currently I am using Ontop with an ontology specification and I am not materializing the mapping assertions.
When you mentioned the option of no ontology, does this mean that Ontop materialize into a knowledge graph the mappings of  the data sources when no ontology is present? (and therefore the rebranding from OBDA into VKG)
I am trying to understand better.

Best regards,
Edlira

**Comment by bcogrel** [comment]
Ontop is intended to be used with a non-empty mapping, because its main functionality consists in translating SPARQL queries into SQL ones. If you have an ontology and an empty mapping, the SQL queries will not make any use of the data stored in the database, only data provided by the SQL query itself. It may work but it is clearly not efficient and is not the right tool for that job.

Materialization is a [side-functionality of Ontop](https://ontop-vkg.org/guide/cli.html#ontop-materialize), where the virtual knowledge graph exposed by Ontop is materialized in a set of RDF files. You can then load these RDF files in the triplestore of your choice.

For answering SPARQL queries, Ontop does not materialize anything.

If you want to have a more detailed introduction to the VKG/OBDA approach, I invite you to have a look at these two papers: https://ontop-vkg.org/guide/#citations .

**Comment by EdliraC** [comment]
Hello Benjamin,

thank you for the explanation. I will look further to the papers.

Regards,
Edlira
