### ISSUE TITLE
QL reasoning and implementing transitivity

### ISSUE THREAD

**Issue by wdduncan** [ontop/ontop#73]
According to your documentation, you support QL reasoning. I'm just learning about OWL profiles. According to the W3 web page:

http://www.w3.org/TR/2008/WD-owl2-profiles-20081008/#OWL_2_QL

QL does not support transitivity. Transitivity is important for a lot of the work that I do. Have you found another way to implement transitivity?

Thanks,
Bill

**Comment by martinrezk** [comment]
Hi Bill,

Yes, you can implement it (and linear recursion in general) at the mapping
level using CTEs in SQL.

http://www.postgresql.org/docs/9.1/static/queries-with.html  (Postgres)

We also have some preliminary support of SWRL with some weak form of
recursion, but it is not in the official release.

Best,

Martin.-

**Comment by ghxiao** [comment]
Hi, 

Transitivity is not in OWL 2 QL. In your case, As @martin suggested, you could try to use CTEs to create a view in your database to simulate recursion. 

Let me make it more clear. After you create views in your database, in your mapping, your can refer to the views. But do not declare CTEs in your mapping directly since Ontop cannot handle those SQL queries properly as source queries.

Please also note that this a hacky solution, because in general the principle of OBDA is not to touch the database. Moreover, I am not sure about the performance, because with such views, many optimisations of ontop cannot be applied -- there are no keys defined over views.

**Comment by martinrezk** [comment]
True... My bad. In the latest release we dont support CTEs in the mappings.

In principle we could prepare a jar with support for SWRL for you. But it
would take some time.

**Comment by wdduncan** [comment]
Thanks. I am not familiar with CTEs. I'll try out your suggestions.

**Comment by wdduncan** [comment]
I read some documentation on common table expressions (CTE). As far as I can tell, this looks applicable for hierarchical data, but my case deals with reasoning across a partonomy, not hierarchy. For example, suppose I have a record in an electronic dental record system structured as follows:

patient id  procedure  tooth   surface  material used
------------   -------------  -------   ---------  -------------------
         1        filling        incisor  facial    resin

In this case, a patient receives a filling in her incisor tooth on the facial surface of the tooth, and resin is used as the filling material.   Ontologically, I would structure this using a parthood relation:

resin part_of facial surface
facial surface part_of incisor
incisor part_of patient 1

If I define part_of as being transitive, then the reasoner can infer that the resin is part of patient 1. 

A subsumption hierarchy is not applicable in this case, since resin is not a kind of facial surface.

As mentioned by @martinrezk, this could be done using SWRL rules. However, I do not think a CTE would be a good solution in this case. 

Your thoughts?

-- Bill

**Comment by martinrezk** [comment]
Hi Bill,

If I understand correctly, then the number of jump that you can do
following part_of is bounded and it is independent of the size of the data,
am I correct?.

If tthat's the case you can do a similar trick than the one we used to
encode transitivity in owl:sameAs in

Ontology-based Integration of Cross-linked Datasets
<https://www.google.it/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCAQFjAAahUKEwitm9uT6ePIAhWGOBoKHazzD7s&url=http%3A%2F%2Fwww.inf.unibz.it%2F~mrezk%2Fpdf%2FtechRep-ISWC15.pdf&usg=AFQjCNH5Q6vXMEeejrlpvoAiKIG4Vvh9_A&sig2=cXEA8V-LKIk1bLJMpgSEbQ&bvm=bv.106130839,d.d2s>

Best,

Martin.-

**Comment by wdduncan** [comment]
Hi Martin,
If I understand you correctly, then, yes, part_of is unbounded and independent of the size of the data.

Thanks for the pointer to the paper. I glanced at it, and it looks a bit technical. I'll have to find time to work through it before I can know if it address part_of relations.

Thanks,
Bill

**Comment by marianormuro** [comment]
Hi Bill, I think the basic idea is, since you know how long the part_of
chain is, you can make mappings for them, either manually or with a
procedure (I think
an implementation of that procedure is in the paper). For example:

If you know you have two levels of part of, one between cars and engines,
another between engines and bolts, you would have as a base the following
mappings:

mapping 1
:engine-{engineid} part-of :car-{cardid} .
SQLQUERY1

mapping 2
:bolt-{boltid} part-of :engine-{engineid}
SQLQUERY2

Then, either manually or through a script you can generate automatically
the following mapping:

mapping3
:joint-{subquery2.boltid} part-of :car-{carid}
SELECT .... FROM ( SQLQUERY1 ) subquery1 JOIN ( SQLQUERY2) ON
subquery1.engineid = subquery2.engineid

If its many mappings this has to be automated (too much maual work). The
algorithm goes like this:

1. Find all pairs of "part-of" mappings that could be JOINED either in
subject to object OR object to subject
2. For each pair
        create a new mapping where with the sbuject of mapping1, andthe
object of mapping 2 (or viceversa) and use an SQL query of the form
        SELECT * FROM (SQL query for mapping 1) partofsubquery1 JOIN (SQL
query for mapping2) partofsubquery2 ON (here goes the join condition)
3. Repeat until you can't generate more mappings

Note that altough this combines part-of mappings exponentially (N x N) in
practice things are more limited since not every subject joins with every
object, etc.













On Wed, Oct 28, 2015 at 10:54 AM, Bill Duncan <notifications@github.com>
wrote:

> Hi Martin,
> If I understand you correctly, then, yes, part_of is unbounded and
> independent of the size of the data.
>
> Thanks for the pointer to the paper. I glanced at it, and it looks a bit
> technical. I'll have to find time to work through it before I can know if
> it address part_of relations.
>
> Thanks,
> Bill
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ontop/ontop/issues/73#issuecomment-151871394>.
>



-- 

Mariano Rodriguez Muro
http://www.rodriguez-muro.com
https://w3-connections.ibm.com/profiles/html/profileView.do?uid=3G3860897

Research Staff, IBM Research
IBM T.J. Watson research center
Yorktown heights, NY. USA
+1-914-945-2607

home: mariano.muro@gmail.com
work: mrodrig@us.ibm.com

**Comment by ghxiao** [comment]
I close this issue for the moment. @wdduncan if you have more comments, just reopen it :)
