### ISSUE TITLE
In objectMap two distinct SQL queries without rr:joinCondition must result in cross-joins

### ISSUE THREAD

**Issue by samdus** [ontop/ontop#791]
### Description

We may use a cross-join between two logical tables when defining an R2RML mapping for an object property. The way to achieve this is to define a rr:objectMap without specifying a rr:joinCondition. Moreover, R2RML [specifies](https://www.w3.org/TR/r2rml/#foreign-key) :

> A referencing object map is represented by a resource that **may** have one or more rr:joinCondition properties, whose values must be join conditions.

Therefore, the join conditions are optional, and Ontop should support object maps without rr:joinCondition. Unfortunately, R2RMLToSQLPPTriplesMapConverter will throw an exception if the objectMap doesn't contain a rr:joinCondition and the two SQL queries are different.

### Steps to Reproduce

1. Create an object property mapping object property without specifying a rr:joinCondition
3. Load the query engine with the mapping
4. The exception is thrown before the load is completed.

**Expected behavior:** [What you expect to see]
The query engine loads successfully. The query generated for the object property contains a cross-join if the logicalTable refers to a table. The query generated for the object property contains the added constant if the logicalTable refers to a constant.

**Actual behavior:** [What actually happens]
The exception is thrown: 
````
java.lang.IllegalArgumentException: No rr:joinCondition, but the two SQL queries are distinct: [...]
	at it.unibz.inf.ontop.spec.mapping.parser.impl.R2RMLToSQLPPTriplesMapConverter.getRefSQLPPTriplesMaps(R2RMLToSQLPPTriplesMapConverter.java:203)
````

**Reproduces how often:** [Does it happen every time?]
Reproduces every time.

### Attached material

An example mapping can be found here: https://github.com/samdus/ontop/tree/bugfix/emptyJoinConditionSupport/test/docker-tests/src/test/resources/issue791

### Versions

Current "version5" branch (as of 2024-02-22, commit 6216b518f37425a670ec29f4a02fd409e1b8c9f8).

**Comment by kontchakov** [comment]
Hi Samuel 

Thanks for the proposed fix. The [R2RML specification](https://www.w3.org/TR/r2rml/#foreign-key), however, says 

"If the [child query](https://www.w3.org/TR/r2rml/#dfn-child-query) and [parent query](https://www.w3.org/TR/r2rml/#dfn-parent-query) of a [referencing object map](https://www.w3.org/TR/r2rml/#dfn-referencing-object-map) are not identical, then the referencing object map must have at least one [join condition](https://www.w3.org/TR/r2rml/#dfn-join-condition)."

It also says the following on the joint SQL query:

"If the referencing object map has no [join condition](https://www.w3.org/TR/r2rml/#dfn-join-condition):
`SELECT * FROM ({child-query}) AS tmp`"

It looks like these two imply that if there is no join condition then (a) the child and the parent query must be identical (this is the contraposition of the first cited sentence) and (b) the joint SQL query is simply the child query, without any cross-joins. Is it not the case?

Thanks

Roman

**Comment by samdus** [comment]
Thank you for your time! Obviously, you are right. I misread the documentation because I was convinced it was a critical use case. Do you know why the decision to prevent cross-joins was made in the R2RML specification? 

I'm considering a way to support this case while respecting the specification, but I'd like to know if there's some logical issue I need help finding.

Thanks again,
Samuel

**Comment by kontchakov** [comment]
Hi Samuel

The solution in the R2RML specification makes perfect sense for denormalized data, when both the parent and the child queries give you the same set of tuples. 

I have had a look at your [mapping](https://github.com/samdus/ontop/blob/bugfix/emptyJoinConditionSupport/test/docker-tests/src/test/resources/issue791/mapping.ttl), and cannot see it work really. The part with ID `Mapping:IAO_0000032_height` creates class assertions of the form `obo:IAO_0000032(http://purl.obolibrary.org/obo/IAO_0000032/{\"id\"})`, which is fine. But then the SQL query in `Mapping:IAO_0000003_height_label` selects only `unit`s, which means that the connection between the measurement ID and its units is completely lost (if you look at this mapping in isolation). If you were really after the cross-product of the two queries, then the result would be somewhat strange: for example, two rows `1, 150, cm` and `2, 6, ft` in the table would give you 4 combinations `1-150cm`, `1-150ft`, `2-6ft` and `2-6cm` (this is because the "units" query does not contain IDs) - I do not think this is intended. What would make sense in your case is to replace both SQL queries with the same `select * from \"height_measurement\"` (or even better use `rr:tableName`) - then the connection between the height and its units would not be lost (it would be "preserved" through the ID). And this is precisely the restriction from the R2RML standard - that the two queries are identical. 

Note also that there is no need in the `not null` filters as R2RML takes care of that - see 
 [term generation rules](https://www.w3.org/TR/r2rml/#generated-rdf-term).

Best
Roman

**Comment by samdus** [comment]
Thank you for your time! 

I realized that the example with the height measurement was unfortunate, but I didn't find a better example of cross-join on top of my head. Indeed, the cross-join between two expressions with a cardinality higher than one is rare in real-life cases, yet I don't think it's a sufficient reason to forbid them in R2RML explicitly. Moreover, I believe that cross-joins with an expression returning only one row could still be helpful because it allows extending the expression with a constant or with the result of a function.

That said, even though I was disappointed, I agree that it's not an essential issue since most of the time, the mapper will be able to write the logical table in a way that a `joinCondition` can be written (without any impact on the performance or the expressivity). For instance, in my example, I could have written:

```

<Mapping:IAO_0000032_weight>
    a               rr:TriplesMap ;
    rr:logicalTable [ a           rr:R2RMLView ;
                      rr:sqlQuery "select \"id\" from \"weight_measurement\" where \"weight\" is not null" ] ;
    rr:subjectMap   [ a           rr:SubjectMap, rr:TermMap ;
                      rr:class    obo:IAO_0000032 ;
                      rr:template "http://purl.obolibrary.org/obo/IAO_0000032/{\"id\"}" ;
                      rr:termType rr:IRI ] .

<Mapping:IAO_0000003_kg>
    a               rr:TriplesMap ;
    rr:logicalTable [ a           rr:R2RMLView ;
                      rr:sqlQuery "select \"id\", \"get_unit\"() as \"unit\" from \"weight_measurement\"" ] ;
    rr:subjectMap   [ a           rr:SubjectMap, rr:TermMap ;
                      rr:class    obo:IAO_0000003 ;
                      rr:template "http://purl.obolibrary.org/obo/IAO_0000003/{\"unit\"}" ;
                      rr:termType rr:IRI ] .

<Mapping:IAO_0000032_weight>
    rr:predicateObjectMap [ rr:predicate obo:IAO_0000039 ;
                            rr:objectMap [ rr:parentTriplesMap <Mapping:IAO_0000003_kg> ;
                                           rr:joinCondition    [ rr:child  "\"id\"" ;
                                                                 rr:parent "\"id\"" ] ] ] .
```

Finally, thank you for pointing out the redundant `not null` in `Mapping:IAO_0000003_height_label`. It's a habit I try to lose when writing mappings!

Thanks again for your time; I will close this issue.
